#!/bin/sh

set -e

# variables
LIVE_CONF=${HOME}/Config
OWN_CONF=${HOME}/work
MAP_LIST='maps.txt'

# merge live ini files with own custom values
# these must be unique for crudini to work
# the rest will be generated by this script
for f in $(find ${CONF} *.ini -type f -printf %f\\n)
do
    crudini --merge ${LIVE_CONF}/${f} < ${OWN_CONF}/${f}
done

# delete old workshop section from KFEngine altogether
crudini --del ${LIVE_CONF}/LinuxServer-KFEngine.ini OnlineSubsystemSteamworks.KFWorkshopSteamworks

# also reset download managers, we need multiple values and in specific order
crudini --del ${LIVE_CONF}/LinuxServer-KFEngine.ini IpDrv.TcpNetDriver DownloadManagers
crudini --set ${LIVE_CONF}/LinuxServer-KFEngine.ini IpDrv.TcpNetDriver DownloadManagers OnlineSubsystemSteamworks.SteamWorkshopDownload
sed -i 's/DownloadManagers.*=.*OnlineSubsystemSteamworks.SteamWorkshopDownload/&\nDownloadManagers=IpDrv.HTTPDownload/' ${LIVE_CONF}/LinuxServer-KFEngine.ini

# workshop header
echo '[OnlineSubsystemSteamworks.KFWorkshopSteamworks]' >> ${LIVE_CONF}/LinuxServer-KFEngine.ini

# parse map list
while IFS='' read -r line || [[ -n "${line}" ]]
do
    ID=$(awk -F "," '{print $1}' <<< ${line})
    NAME=$(awk -F "," '{print $2}' <<< ${line})

    # add entry to workshop list, can't use crudini here because parameters aren't unique
    echo "ServerSubscribedWorkshopItems=${ID}" >> ${LIVE_CONF}/LinuxServer-KFEngine.ini

    # delete old entry from KFGame list to make sure all custom entries are at the end
    crudini --del ${LIVE_CONF}/LinuxServer-KFGame.ini "${NAME} KFMapSummary"

    # add new entry to KFGame list
    crudini --set ${LIVE_CONF}/LinuxServer-KFGame.ini "${NAME} KFMapSummary" "MapName" "${NAME}"
done < ${MAP_LIST}

# cleanup
for INI in 'LinuxServer-KFEngine.ini' 'LinuxServer-KFGame.ini'
do
    # delete repeated newlines
    cp ${LIVE_CONF}/${INI} ${LIVE_CONF}/${INI}.tmp
    cat -s ${LIVE_CONF}/${INI}.tmp > ${LIVE_CONF}/${INI}
    rm ${LIVE_CONF}/${INI}.tmp

    # get rid of spaces around = added by crudini
    sed -i 's/ = /=/' ${LIVE_CONF}/${INI}
done
