#!/bin/sh

set -e

# variables
LIVE_CONF="${HOME}/Steam/KF2Server/KFGame/Config"
OWN_CONF="${HOME}/work"
MAP_DIR="${HOME}/Steam/KF2Server/KFGame/BrewedPC/Maps"
MAP_LIST='maps.txt'
CYCLE_LIST='cycles.txt'

# merge live ini files with own custom values
# these must be unique for crudini to work
# the rest will be generated by this script
for f in $(find ${OWN_CONF} -maxdepth 1 -name '*.ini' -type f -printf %f\\n)
do
    crudini --merge ${LIVE_CONF}/${f} < ${OWN_CONF}/${f}
done

# delete old workshop section from KFEngine altogether
crudini --del ${LIVE_CONF}/LinuxServer-KFEngine.ini OnlineSubsystemSteamworks.KFWorkshopSteamworks

# also reset download managers, we need multiple values and in specific order
crudini --del ${LIVE_CONF}/LinuxServer-KFEngine.ini IpDrv.TcpNetDriver DownloadManagers
crudini --set ${LIVE_CONF}/LinuxServer-KFEngine.ini IpDrv.TcpNetDriver DownloadManagers OnlineSubsystemSteamworks.SteamWorkshopDownload
sed -i 's/DownloadManagers.*=.*OnlineSubsystemSteamworks.SteamWorkshopDownload/&\nDownloadManagers=IpDrv.HTTPDownload/' ${LIVE_CONF}/LinuxServer-KFEngine.ini

# workshop header
echo '[OnlineSubsystemSteamworks.KFWorkshopSteamworks]' >> ${LIVE_CONF}/LinuxServer-KFEngine.ini

# delete old cycles
crudini --del ${LIVE_CONF}/LinuxServer-KFGame.ini KFGame.KFGameInfo GameMapCycles

# cycle string
CYCLE_START='GameMapCycles=(Maps=('

# parse custom cycle list
while IFS='' read -r line || [[ -n "${line}" ]]
do
    CYCLE="${CYCLE_START}\"${line}\"))"
    CYCLE=$(sed 's/,/","/g' <<< ${CYCLE})
    sed -i "s/\[KFGame.KFGameInfo\]/&\n${CYCLE}/" ${LIVE_CONF}/LinuxServer-KFGame.ini
done < ${CYCLE_LIST}

# cycle string reset
CYCLE="${CYCLE_START}"
# track if we need a comma or not
FIRST=1

# parse map list
while IFS='' read -r line || [[ -n "${line}" ]]
do
    ID=$(awk -F "," '{print $1}' <<< ${line})
    NAME=$(awk -F "," '{print $2}' <<< ${line})

    # add entry to workshop list, can't use crudini here because parameters aren't unique
    echo "ServerSubscribedWorkshopItems=${ID}" >> ${LIVE_CONF}/LinuxServer-KFEngine.ini

    # delete old entry from KFGame list to make sure all custom entries are at the end
    crudini --del ${LIVE_CONF}/LinuxServer-KFGame.ini "${NAME} KFMapSummary"

    # add new entry to KFGame list
    crudini --set ${LIVE_CONF}/LinuxServer-KFGame.ini "${NAME} KFMapSummary" "MapName" "${NAME}"

    # construct the workshop map cycle
    if [ ${FIRST} -ne 1 ]
    then
        CYCLE="${CYCLE},"
    fi
    CYCLE="${CYCLE}\"${NAME}\""
    FIRST=0
done < ${MAP_LIST}

# write the workshop map cycle
CYCLE="${CYCLE}))"
sed -i "s/\[KFGame.KFGameInfo\]/&\n${CYCLE}/" ${LIVE_CONF}/LinuxServer-KFGame.ini

# reset
CYCLE="${CYCLE_START}"
FIRST=1

# cycle for stock maps
for d in $(find ${MAP_DIR} -maxdepth 1 -mindepth 1 -type d -printf %f\\n)
do
    if [ ${FIRST} -ne 1 ]
    then
        CYCLE="${CYCLE},"
    fi
    CYCLE="${CYCLE}\"KF-${d}\""
    FIRST=0
done

# always do default maps last so that it is the first cycle in the config
CYCLE="${CYCLE}))"
sed -i "s/\[KFGame.KFGameInfo\]/&\n${CYCLE}/" ${LIVE_CONF}/LinuxServer-KFGame.ini

# cleanup
for INI in 'LinuxServer-KFEngine.ini' 'LinuxServer-KFGame.ini'
do
    # delete repeated newlines
    cp ${LIVE_CONF}/${INI} ${LIVE_CONF}/${INI}.tmp
    cat -s ${LIVE_CONF}/${INI}.tmp > ${LIVE_CONF}/${INI}
    rm ${LIVE_CONF}/${INI}.tmp

    # get rid of spaces around = added by crudini
    sed -i 's/ = /=/' ${LIVE_CONF}/${INI}
done
