- name: Check the state of system services
  service_facts:

- name: Check if KF2 firewall rules are present
  stat:
    path: /etc/firewalld/services/kf2.xml
  register: kf2_fw_file

- name: Disable KF2 firewall rules
  firewalld:
    service: kf2
    permanent: yes
    immediate: yes
    state: disabled
  when: ansible_facts.services["firewalld.service"] is defined and ansible_facts.services["firewalld.service"].state == "running" and kf2_fw_file.stat.exists

- name: Delete KF2 firewall rules
  file:
    path: /etc/firewalld/services/kf2.xml
    state: absent
  register: kf2_fw_delete

- name: Reload firewalld config
  command:
    cmd: firewall-cmd --reload
  when: ansible_facts.services["firewalld.service"] is defined and ansible_facts.services["firewalld.service"].state == "running" and kf2_fw_delete.changed
