---
- include_role:
    name: bviktor.firewalld
  vars:
    service: 'kf2'
    enabled: false

- name: Remove firewalld log redirect
  file:
    path: /etc/rsyslog.d/firewalld-denied.conf
    state: absent
  notify: Reload rsyslog configuration

- name: Remove firewalld log rotation
  file:
    path: /etc/logrotate.d/firewalld-denied
    state: absent

- name: Remove log throttling checker wrapper script
  file:
    path: /usr/local/bin/check-log-throttling
    state: absent
