- name: Remove killinuxfloor
  file:
    path: "{{ steam_home }}/killinuxfloor"
    state: absent

- name: Remove killinuxfloor commands
  file:
    path: "{{ steam_home }}/bin/{{ item }}"
    state: absent
  loop:
  - killinuxfloor
  - klf
  - kf2-centos
  - kf2watchdog

- name: Remove DepotDownloader
  file:
    path: "{{ steam_home }}/depotdownloader"
    state: absent
