- name: Check killinuxfloor SELinux policy module status
  shell:
    cmd: semodule --list | grep killinuxfloor
  failed_when: no
  changed_when: no
  register: klf_selinux

- name: Disable SELinux policy module
  command:
    cmd: semodule --remove=killinuxfloor
  when: klf_selinux.rc == 0

- name: Delete SELinux policy module
  file:
    path: "{{ semodule_dir }}/killinuxfloor.cil"
    state: absent
