---
- name: Check killinuxfloor SELinux policy module status
  shell:
    cmd: semodule --list | grep killinuxfloor
  failed_when: false
  changed_when: false
  register: klf_selinux

- name: Disable SELinux policy module
  command:
    cmd: semodule --remove=killinuxfloor
  when: klf_selinux.rc == 0

- name: Delete SELinux policy module
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ steam_home }}/selinux"
  - "{{ semodule_dir }}/killinuxfloor.cil"
