- name: Check the state of system services
  service_facts:

- name: Check systemd status
  command:
    cmd: systemctl is-system-running
  failed_when: no
  changed_when: no
  register: systemd_running

- name: Stop and disable the KF2 service
  systemd:
    name: kf2
    state: stopped
    enabled: no
  when: ansible_facts.services["kf2.service"] is defined

- name: Stop and disable the KF2 autokick service
  systemd:
    name: kf2autokick
    state: stopped
    enabled: no
  when: ansible_facts.services["kf2autokick.service"] is defined

- name: Stop and disable the KF2 watchdog service
  systemd:
    name: kf2watchdog
    state: stopped
    enabled: no
  when: ansible_facts.services["kf2watchdog.service"] is defined

- name: Remove KF2 services
  file:
    path: "/etc/systemd/system/{{ item }}"
    state: absent
  loop:
  - kf2.service
  - kf2autokick.service
  - kf2watchdog.service
  notify: Reload systemd configuration

- name: Remove service extra files
  file:
    path: /etc/systemd/system/kf2.service.d
    state: absent

- meta: flush_handlers
