---
- include_role:
    name: bviktor.servicecheck
  vars:
    unit: kf2.service

- name: Stop and disable the KF2 service
  systemd:
    name: kf2.service
    state: stopped
    enabled: false
  when: servicecheck.exists

- include_role:
    name: bviktor.servicecheck
  vars:
    unit: kf2autokick.service

- name: Stop and disable the KF2 autokick service
  systemd:
    name: kf2autokick.service
    state: stopped
    enabled: false
  when: servicecheck.exists

- include_role:
    name: bviktor.servicecheck
  vars:
    unit: kf2watchdog.service

- name: Stop and disable the KF2 watchdog service
  systemd:
    name: kf2watchdog.service
    state: stopped
    enabled: false
  when: servicecheck.exists

- name: Remove KF2 services
  file:
    path: "/etc/systemd/system/{{ item }}"
    state: absent
  loop:
    - kf2.service
    - kf2autokick.service
    - kf2watchdog.service
  notify: Reload systemd configuration

- name: Remove service extra files
  file:
    path: /etc/systemd/system/kf2.service.d
    state: absent

- meta: flush_handlers
