---
- name: Reload systemd configuration
  systemd:
    daemon_reload: true
  when: servicecheck.systemd

- name: Reload rsyslog configuration
  systemd:
    name: rsyslog.service
    state: restarted

- name: Reload journald configuration
  systemd:
    name: systemd-journald.service
    state: restarted
