---
date_str: "{{ ansible_facts['date_time'].year }}{{ ansible_facts['date_time'].month }}{{ ansible_facts['date_time'].day }}-{{ ansible_facts['date_time'].hour }}{{ ansible_facts['date_time'].minute }}{{ ansible_facts['date_time'].second }}"
