#!/bin/sh

set -Eeu

function errorexit ()
{
    case $? in
        1)
            echo "Usage: $0 {start|stop|restart|status|update|log|config}"
            ;;

        2)
            echo 'error!'
            ;;

    esac
}

trap errorexit EXIT

function regen_conf ()
{
    # variables
    LIVE_CONF="${HOME}/Steam/KF2Server/KFGame/Config"
    OWN_CONF="${HOME}/Config"
    MAP_DIR="${HOME}/Steam/KF2Server/KFGame/BrewedPC/Maps"
    MAP_LIST="${OWN_CONF}/My-Maps.csv"
    CYCLE_LIST="${OWN_CONF}/My-Cycles.csv"

    # merge live ini files with own custom values
    # these must be unique for crudini to work
    # the rest will be generated by this script
    echo -n 'Applying settings to upstream config files... '
    for f in $(find ${OWN_CONF} -maxdepth 1 -name '*.ini' -type f -printf %f\\n)
    do
        crudini --merge "${LIVE_CONF}/${f#$"My-"}" < "${OWN_CONF}/${f}"
    done
    echo 'done.'

    # delete old workshop section from KFEngine altogether
    echo -n 'Deleting old workshop entries... '
    crudini --del ${LIVE_CONF}/LinuxServer-KFEngine.ini OnlineSubsystemSteamworks.KFWorkshopSteamworks
    echo 'done.'

    # also reset download managers, we need multiple values and in specific order
    echo -n 'Configuring map download managers... '
    crudini --del ${LIVE_CONF}/LinuxServer-KFEngine.ini IpDrv.TcpNetDriver DownloadManagers
    crudini --set ${LIVE_CONF}/LinuxServer-KFEngine.ini IpDrv.TcpNetDriver DownloadManagers OnlineSubsystemSteamworks.SteamWorkshopDownload
    sed -i 's/DownloadManagers.*=.*OnlineSubsystemSteamworks.SteamWorkshopDownload/&\nDownloadManagers=IpDrv.HTTPDownload/' ${LIVE_CONF}/LinuxServer-KFEngine.ini
    echo 'done.'

    # delete old cycles
    echo -n 'Deleting old game cycles... '
    crudini --del ${LIVE_CONF}/LinuxServer-KFGame.ini KFGame.KFGameInfo GameMapCycles
    echo 'done.'

    # cycle string
    CYCLE_START='GameMapCycles=(Maps=('

    # parse custom cycle list
    echo -n 'Adding custom game cycles... '
    test -e ${CYCLE_LIST} || exit 2
    while read -r line
    do
        # skip comments
        [[ $line = \#* ]] && continue
        CYCLE="${CYCLE_START}\"${line}\"))"
        CYCLE=$(sed 's/,/","/g' <<< ${CYCLE})
        sed -i "s/\[KFGame.KFGameInfo\]/&\n${CYCLE}/" ${LIVE_CONF}/LinuxServer-KFGame.ini
    done < ${CYCLE_LIST}
    echo 'done.'

    # cycle string reset
    CYCLE="${CYCLE_START}"
    # track if we need a comma or not
    FIRST=1

    # workshop header
    echo '[OnlineSubsystemSteamworks.KFWorkshopSteamworks]' >> ${LIVE_CONF}/LinuxServer-KFEngine.ini

    # parse map list
    echo -n 'Applying workshop subscriptions and updating webadmin map entries... '
    test -e ${MAP_LIST} || exit 2
    while read -r line
    do
        # skip comments
        [[ $line = \#* ]] && continue
        ID=$(awk -F "," '{print $1}' <<< ${line})
        NAME=$(awk -F "," '{print $2}' <<< ${line})

        # add entry to workshop list, can't use crudini here because parameters aren't unique
        echo "ServerSubscribedWorkshopItems=${ID}" >> ${LIVE_CONF}/LinuxServer-KFEngine.ini

        # delete old entry from KFGame list to make sure all custom entries are at the end
        crudini --del ${LIVE_CONF}/LinuxServer-KFGame.ini "${NAME} KFMapSummary"

        # add new entry to KFGame list
        crudini --set ${LIVE_CONF}/LinuxServer-KFGame.ini "${NAME} KFMapSummary" "MapName" "${NAME}"

        # construct the workshop map cycle
        if [ ${FIRST} -ne 1 ]
        then
            CYCLE="${CYCLE},"
        fi
        CYCLE="${CYCLE}\"${NAME}\""
        FIRST=0
    done < ${MAP_LIST}
    echo 'done.'

    # write the workshop map cycle
    echo -n 'Adding map cycle for workshop maps... '
    CYCLE="${CYCLE}))"
    sed -i "s/\[KFGame.KFGameInfo\]/&\n${CYCLE}/" ${LIVE_CONF}/LinuxServer-KFGame.ini
    echo 'done.'

    # reset
    CYCLE="${CYCLE_START}"
    FIRST=1

    # cycle for stock maps
    echo -n 'Adding map cycle for stock maps... '
    for d in $(find ${MAP_DIR} -maxdepth 1 -mindepth 1 -type d -printf %f\\n)
    do
        if [ ${FIRST} -ne 1 ]
        then
            CYCLE="${CYCLE},"
        fi
        CYCLE="${CYCLE}\"KF-${d}\""
        FIRST=0
    done

    # always do default maps last so that it is the first cycle in the config
    CYCLE="${CYCLE}))"
    sed -i "s/\[KFGame.KFGameInfo\]/&\n${CYCLE}/" ${LIVE_CONF}/LinuxServer-KFGame.ini
    echo 'done.'

    # cleanup
    echo -n 'Making sure INI files are formatted properly... '
    for INI in 'LinuxServer-KFEngine.ini' 'LinuxServer-KFGame.ini'
    do
        # delete repeated newlines
        cp ${LIVE_CONF}/${INI} ${LIVE_CONF}/${INI}.tmp
        cat -s ${LIVE_CONF}/${INI}.tmp > ${LIVE_CONF}/${INI}
        rm ${LIVE_CONF}/${INI}.tmp

        # get rid of spaces around = added by crudini
        sed -i 's/ = /=/' ${LIVE_CONF}/${INI}
    done
    echo 'done.'

    echo 'Killing Floor 2 server configuration regenerated successfully!'
}

if [ "$#" -ne 1 ]
then
    exit 1
fi

case $1 in
    start)
        sudo /bin/systemctl start kf2.service
        ;;

    stop)
        sudo /bin/systemctl stop kf2.service
        ;;

    restart)
        sudo /bin/systemctl restart kf2.service
        ;;

    status)
        sudo /bin/systemctl status kf2.service
        ;;

    update)
        steamcmd.sh +login anonymous +force_install_dir ./KF2Server +app_update 232130 +exit
        ;;

    log)
        sudo /bin/journalctl --system --unit=kf2.service --follow
        ;;

    config)
        regen_conf
        ;;

    *)
        exit 1

esac
