#!/bin/bash

set -eu

echo "$(date --rfc-3339=seconds) KF2 Watchdog started" | tee -a /home/steam/Steam/logs/kf2watchdog.txt

while true
do
    # this shouldn't be needed since the watchdog service depends on the KF2 service
    # but it doesn't hurt to check anyway
    if [ $(/bin/systemctl is-active kf2.service) ]
    then
        # give enough time for map changes and even workshop -> cache flushes
        RET=1
        curl -L -s -S --connect-timeout 120 --retry 10 --retry-connrefused --retry-delay 10 localhost:8080 > /dev/null && RET=$? || true

        if [ ${RET} -ne 0 ]
        then
            echo "$(date --rfc-3339=seconds) KF2 restarted" | tee -a /home/steam/Steam/logs/kf2watchdog.txt
            sudo /bin/systemctl restart kf2.service
        fi
    fi
    sleep 60
done
