---
# TODO DNF modules used to be the way, but apparently not anymore
#name: "@nodejs:{{ nodejs_version }}/common"
- name: Install Node.js
  package:
    name: nodejs
    state: latest

- include_role:
    name: noobient.thirdparty
  vars:
    name: Yarn
    gpg_url: "https://dl.yarnpkg.com/{% if ansible_os_family == 'RedHat' %}rpm{% else %}debian{% endif %}/pubkey.gpg"
    repo_file: yarn
    package: yarn

- name: Obtain kf2_autokick sources
  become_user: steam
  git:
    repo: https://github.com/Sinewyk/kf2_autokick.git
    dest: "{{ steam_home }}/kf2autokick"
    force: true
  register: autokick_git

- name: Build kf2_autokick # noqa no-handler no-changed-when
  become_user: steam
  shell:
    cmd: "cd {{ steam_home }}/kf2autokick && yarn --silent --prod --frozen-lockfile"
  when: autokick_git.changed
