---
# use dnf modules
- name: Install Node.js
  dnf:
    name: "@nodejs:{{ nodejs_version }}/common"
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Install Node.js
  apt:
    name: "nodejs"
    state: latest
  when: ansible_os_family == 'Debian'

- include_role:
    name: bviktor.thirdparty
  vars:
    name: Yarn
    gpg_url: "https://dl.yarnpkg.com/{% if ansible_os_family == 'RedHat' %}rpm{% else %}debian{% endif %}/pubkey.gpg"
    repo_file: yarn
    package: yarn

- name: Obtain kf2_autokick sources
  become: true
  become_user: steam
  git:
    repo: https://github.com/Sinewyk/kf2_autokick.git
    dest: "{{ steam_home }}/kf2autokick"
    force: true
  register: autokick_git

- name: Build kf2_autokick # noqa no-handler
  become: true
  become_user: steam
  shell:
    cmd: "cd {{ steam_home }}/kf2autokick && yarn --silent --prod --frozen-lockfile"
  when: autokick_git.changed
