---
# use dnf modules
- name: Install Node.js
  dnf:
    name: "@nodejs:18/common"
    state: present

- name: Import Yarn GPG key
  rpm_key:
    state: present
    key: https://dl.yarnpkg.com/rpm/pubkey.gpg

- name: Install Yarn repo
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo

- name: Install Yarn
  dnf:
    name: yarn
    state: latest

- name: Obtain kf2_autokick sources
  become: true
  become_user: steam
  git:
    repo: https://github.com/Sinewyk/kf2_autokick.git
    dest: "{{ steam_home }}/kf2autokick"
    force: yes
  register: autokick_git

- name: Build kf2_autokick
  become: true
  become_user: steam
  shell:
    cmd: "cd {{ steam_home }}/kf2autokick && yarn --silent --prod --frozen-lockfile"
  when: autokick_git.changed
