---
# use dnf modules
- name: Install Node.js
  dnf:
    name: "@nodejs:{{ nodejs_version }}/common"
    state: present

- include_role:
    name: bviktor.thirdparty
  vars:
    - name: Yarn
    - gpg_url: https://dl.yarnpkg.com/rpm/pubkey.gpg
    - repo_url: https://dl.yarnpkg.com/rpm/yarn.repo
    - package: yarn

- name: Obtain kf2_autokick sources
  become: true
  become_user: steam
  git:
    repo: https://github.com/Sinewyk/kf2_autokick.git
    dest: "{{ steam_home }}/kf2autokick"
    force: true
  register: autokick_git

- name: Build kf2_autokick # noqa no-handler
  become: true
  become_user: steam
  shell:
    cmd: "cd {{ steam_home }}/kf2autokick && yarn --silent --prod --frozen-lockfile"
  when: autokick_git.changed
