---
# Fedora has the EPEL packages in main
- include_tasks: epel.yml
  when: ansible_distribution != 'Fedora'

- name: Install config generator
  dnf:
    name: crudini
    state: latest
    update_cache: true

- name: Create Config directory
  file:
    path: "{{ steam_home }}/Config"
    state: directory
    owner: steam
    group: steam

- name: Deploy default config
  copy:
    src: "Config/{{ item }}"
    dest: "{{ steam_home }}/Config/{{ item }}"
    backup: true
    owner: steam
    group: steam
  loop:
    - My-Cycles.csv
    - My-KFWebAdmin.ini
    - My-KFWeb.ini
    - My-LinuxServer-KFEngine.ini
    - My-LinuxServer-KFGame.ini
    - My-Maps.csv
    - My-Mutators.csv
    - My-Startup.conf
    - autokick.json
  notify: Reload systemd configuration

- name: Link KF2 startup config to systemd folder
  file:
    src: "{{ steam_home }}/Config/My-Startup.conf"
    dest: /etc/systemd/system/kf2.service.d/kf2.service.conf
    state: link
    force: true
    follow: false
  notify: Reload systemd configuration

- meta: flush_handlers

- name: Make symlink to internal config
  file:
    src: "{{ steam_home }}/Steam/KF2Server/KFGame/Config"
    dest: "{{ steam_home }}/Config/Internal"
    state: link
    force: true
    follow: false
    owner: steam
    group: steam
