---
- include_role:
    name: bviktor.servicecheck
  vars:
    unit: firewalld.service

- include_role:
    name: bviktor.firewalld
  vars:
    service: 'kf2'
    port: "{{ item }}"
  loop:
    - '7777/udp'
    - '20560/udp'
    - '27015/udp'
    - '8080/tcp'
  when: servicecheck.started
