---
- name: Install rsyslog
  package:
    name: rsyslog
    state: latest

# On AlmaLinux 8 it's part of rsyslog, after that, it's a separate package...
- name: Install log rotation for system logs
  package:
    name: rsyslog-logrotate
    state: latest
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int >= 9

- name: Enable rsyslog
  systemd:
    name: rsyslog.service
    state: started
    enabled: true

- name: Redirect logging of denied packets
  copy:
    src: firewalld-denied.conf
    dest: /etc/rsyslog.d/firewalld-denied.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload rsyslog configuration

- name: Limit journald storage
  ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: SystemMaxUse
    value: 100M
    no_extra_spaces: true
    create: true
    mode: '0644'
    owner: root
    group: root
    backup: true
  notify: Reload journald configuration

- include_role:
    name: noobient.firewalld
  vars:
    service: kf2
    port: "{{ item }}"
    rate_limit: 10/m
    family: ipv4
  loop:
    - 7777/udp
    - 20560/udp
    - 27015/udp
    - 8080/tcp

- include_role:
    name: noobient.logrotate
  vars:
    name: firewalld-denied
    pattern: |-
      /var/log/firewalld-denied.log
      /var/log/firewalld-denied-kf2.log
    retention: 7

- name: Install wrapper script for checking log throttling status
  copy:
    src: check-log-throttling
    dest: /usr/local/bin/check-log-throttling
    owner: root
    group: root
    mode: '0755'
