---
- name: Check the state of system services
  service_facts:

- name: Check if HTTPS port is open on firewall
  shell:
    cmd: firewall-cmd --list-services | grep https
  failed_when: false
  changed_when: false
  register: fw_https_open
  when: ansible_facts.services["firewalld.service"] is defined

- name: Deploy KF2 firewall rules
  template:
    src: kf2.xml.j2
    dest: /etc/firewalld/services/kf2.xml
    owner: root
    group: root
    mode: '0644'
  register: kf2_fw
  when: ansible_facts.services["firewalld.service"] is defined

- name: Reload firewalld config
  command:
    cmd: firewall-cmd --reload
  when: kf2_fw.changed and ansible_facts.services["firewalld.service"] is defined and ansible_facts.services["firewalld.service"].state == "running"

- name: Enable KF2 firewall rules
  firewalld:
    service: kf2.service
    permanent: true
    immediate: true
    state: enabled
  when: ansible_facts.services["firewalld.service"] is defined and ansible_facts.services["firewalld.service"].state == "running"
