---
- name: Install rsyslog
  package:
    name: rsyslog
    state: latest

- name: Enable rsyslog
  systemd:
    name: rsyslog.service
    state: started
    enabled: true

- name: Redirect logging of denied packets
  copy:
    src: firewalld-denied.conf
    dest: /etc/rsyslog.d/firewalld-denied.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload rsyslog configuration

- name: Limit journald storage
  ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: SystemMaxUse
    value: 100M
    no_extra_spaces: true
    create: false
    backup: true
  notify: Reload journald configuration

- include_role:
    name: bviktor.firewalld
  vars:
    service: 'kf2'
    port: "{{ item }}"
    rate_limit: '10/m'
  loop:
    - '7777/udp'
    - '20560/udp'
    - '27015/udp'
    - '8080/tcp'

- include_role:
    name: bviktor.logrotate
  vars:
    name: firewalld-denied
    pattern: |-
      /var/log/firewalld-denied.log
      /var/log/firewalld-denied-kf2.log
    retention: 7
