---
# this should work regardless of unit path or service state
- name: Check if firewalld service is present # noqa command-instead-of-module
  command:
    cmd: systemctl cat firewalld.service
  changed_when: false
  failed_when: false
  register: firewalld_present

- name: Check if firewalld service is running # noqa command-instead-of-module
  command:
    cmd: systemctl is-active firewalld.service
  changed_when: false
  failed_when: false
  register: firewalld_running

- include_tasks: firewalld.yml
  when: firewalld_present.rc == 0
