- name: Determine install flavor
  debug:
    msg: "Installing killinuxfloor in Classic mode"
  when: kf2_classic|bool

- name: Determine install flavor
  debug:
    msg: "Installing killinuxfloor in Retail mode"
  when: not kf2_classic|bool
