---
- name: Initialize KF2 config # noqa no-changed-when
  become_user: steam
  command:
    cmd: "{{ steam_home }}/bin/killinuxfloor {{ item }}"
  loop:
    - reset
    - apply
  when: servicecheck.systemd and not skip_kfgame
