---
- include_tasks: flavor.yml
- include_tasks: os.yml
- include_tasks: user.yml

- include_role:
    name: bviktor.selinux_cil
  vars:
    module: killinuxfloor

- include_tasks: steam.yml
- include_tasks: kf2.yml
- include_tasks: systemd.yml
- include_tasks: sudo.yml

- include_role:
    name: bviktor.servicecheck
  vars:
    unit: firewalld.service

- include_tasks: firewalld.yml
  when: servicecheck.started

- include_tasks: config.yml
- include_tasks: autokick.yml
- include_tasks: killinuxfloor.yml
- include_tasks: init.yml
