---
- include_tasks: flavor.yml
- include_tasks: os.yml
- include_tasks: user.yml

- include_role:
    name: bviktor.selinux_cil
  vars:
    module: killinuxfloor

- include_tasks: steam.yml
- include_tasks: kf2.yml
- include_tasks: systemd.yml
- include_tasks: sudo.yml
- include_tasks: firewalld_check.yml
- include_tasks: config.yml
- include_tasks: autokick.yml
- include_tasks: killinuxfloor.yml
- include_tasks: init.yml
