- include_tasks: flavor.yml
- include_tasks: os.yml
- include_tasks: selinux.yml
- include_tasks: steam.yml

- include_tasks: kf2.yml
  when: not kf2_classic|bool
- include_tasks: kf2classic.yml
  when: kf2_classic|bool

- include_tasks: systemd.yml
- include_tasks: sudo.yml
- include_tasks: firewalld.yml
- include_tasks: config.yml
- include_tasks: autokick.yml
- include_tasks: killinuxfloor.yml
- include_tasks: init.yml
