- name: Check distribtution flavor
  fail:
    msg: 'Sorry, killinuxfloor only supports Red Hat-based distributions. Officially supported OS and release: {{ klf_dist }} {{ klf_rel }}.'
  when: ansible_distribution_file_variety != 'RedHat'

# Node.js requires dnf modules
# we could probably mess around to implement idempotent software collection management on EL7, but... effort
- name: Check package manager
  fail:
    msg: 'Sorry, killinuxfloor only supports the DNF package manager.'
  when: ansible_pkg_mgr != 'dnf'

- name: Make sure the OS is up-to-date
  dnf:
    name: '*'
    state: latest

- name: Check the state of system services
  service_facts:

# we don't need to deal with autokick, the unit stops if kf2 stops
- name: Make sure the KF2 service isn't running
  systemd:
    name: kf2
    state: stopped
  when: ansible_facts.services["kf2.service"] is defined
