---
- name: Check distribution flavor
  fail:
    msg: 'Sorry, killinuxfloor only supports Red Hat and Debian-based distributions. Recommended OS and release: {{ klf_dist }} {{ klf_rel }}.'
  when: ansible_os_family != 'RedHat' and ansible_os_family != 'Debian'

# Node.js requires dnf modules
# we could probably mess around to implement idempotent software collection management on EL7, but... effort
- name: Check package manager
  fail:
    msg: 'Sorry, killinuxfloor only supports the DNF and APT package managers.'
  when: ansible_os_family != 'RedHat' and ansible_os_family != 'Debian'

- name: Make sure the OS is up-to-date
  package:
    name: '*'
    state: latest

# Here we check not only the KF2 service, but also systemd state
# Used in e.g. init, config, systemd
- include_role:
    name: noobient.servicecheck
  vars:
    unit: kf2.service

# we don't need to deal with autokick, the unit stops if kf2 stops
- name: Make sure the KF2 service isn't running
  systemd:
    name: kf2
    state: stopped
  when: servicecheck.started
