---
name: AlmaLinux 8

on: # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: []

jobs:

  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3

  docker:
    needs: clone
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: docker build --tag klf-almalinux8 docker/almalinux/8

  almalinux-8:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: AlmaLinux 8
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf klf-almalinux8 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=true' <<< y && ./uninstall.sh <<< y && ./install.sh --extra-vars 'skip_kfgame=true kf2_classic=true' <<< y"
