---
name: AlmaLinux 9

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  pull_request:
    branches: []

jobs:
  ansible-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3
      - name: Test Galaxy role
        run: >
            CONT_ID=$(podman run --rm -v ${{ github.workspace }}:/repo -v /sys/fs/cgroup:/sys/fs/cgroup:ro
            --tmpfs /tmp --tmpfs /run --privileged --detach bviktor/ansible-systemd-almalinux:9) &&
            podman exec ${CONT_ID} /bin/bash -c
            "if [ -f requirements.yml ]; then ansible-galaxy role install --force -r requirements.yml -p ..; fi &&
            dnf -y install firewalld && systemctl start firewalld.service &&
            ./install.sh --extra-vars 'skip_kfgame=true' <<< y &&
            ./uninstall.sh <<< y &&
            ./install.sh --extra-vars 'skip_kfgame=true kf2_classic=true' <<< y" &&
            podman stop ${CONT_ID}
