---
name: AlmaLinux 9

on: # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: []

jobs:

  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3

  docker:
    needs: clone
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: docker build --tag klf-almalinux9 docker/almalinux/9

  almalinux-8:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: AlmaLinux 9
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf klf-almalinux9 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=true' <<< y && ./uninstall.sh <<< y && ./install.sh --extra-vars 'skip_kfgame=true kf2_classic=true' <<< y"
