---
name: AlmaLinux

on: # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: []

jobs:

  clone:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3

  build:
    needs: clone
    runs-on: [self-hosted, Windows]
    steps:
      - name: Build Docker images
        run: |
            docker build --tag klf-almalinux8 docker/almalinux/8
            docker build --tag klf-almalinux9 docker/almalinux/9

  lint:
    needs: build
    runs-on: [self-hosted, Windows]
    steps:
      - name: Lint sources
        # TODO strict ansible-lint
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf klf-almalinux9 /bin/bash -c
            "yamllint --strict --config-file .yamllint . && ansible-lint --config-file .ansible-lint"

  run-previous:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: AlmaLinux 8
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf klf-almalinux8 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=True' <<< y && ./uninstall.sh <<< y"

  run-current:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: AlmaLinux 9
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf klf-almalinux9 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=True' <<< y && ./uninstall.sh <<< y"
