---
name: Fedora

on: # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: []

jobs:

  clone:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3

  build:
    needs: clone
    runs-on: [self-hosted, Windows]
    steps:
      - name: Build Docker images
        run: |
            docker build --tag klf-fedora36 docker/fedora/36
            docker build --tag klf-fedora37 docker/fedora/37

  lint:
    needs: build
    runs-on: [self-hosted, Windows]
    steps:
      - name: Lint sources
        # TODO strict ansible-lint
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf klf-fedora37 /bin/bash -c
            "yamllint --strict --config-file .yamllint . && ansible-lint --config-file .ansible-lint"

  run-previous:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: Fedora 36
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf klf-fedora36 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=True' <<< y && ./uninstall.sh <<< y"

  run-current:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: Fedora 37
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf klf-fedora37 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=True' <<< y && ./uninstall.sh <<< y"
