---
name: killinuxfloor

on: # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: []

jobs:

  clone:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3

  docker:
    needs: clone
    runs-on: [self-hosted, Windows]
    steps:
      - name: Build Docker images
        run: |
            docker build --tag klf-almalinux8 docker/almalinux/8
            docker build --tag klf-almalinux9 docker/almalinux/9
            docker build --tag klf-fedora36 docker/fedora/36
            docker build --tag klf-fedora37 docker/fedora/37
            docker build --tag klf-lint docker/lint

  lint:
    needs: docker
    runs-on: [self-hosted, Windows]
    steps:
      - name: Lint sources
        # TODO strict ansible-lint
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf:ro klf-lint /bin/bash -c
            "yamllint --strict --config-file .yamllint . && ansible-lint --config-file .ansible-lint"

  almalinux-8:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: AlmaLinux 8
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf:ro klf-almalinux8 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=True' <<< y && ./uninstall.sh <<< y"

  almalinux-9:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: AlmaLinux 9
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf:ro klf-almalinux9 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=True' <<< y && ./uninstall.sh <<< y"

  fedora-36:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: Fedora 36
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf:ro klf-fedora36 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=True' <<< y && ./uninstall.sh <<< y"

  fedora-37:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: Fedora 37
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf:ro klf-fedora37 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=True' <<< y && ./uninstall.sh <<< y"
