---
name: killinuxfloor

on: # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: []

jobs:

  clone:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3

  docker:
    needs: clone
    runs-on: [self-hosted, Windows]
    steps:
      - name: Build Docker images
        run: |
            docker build --tag klf-almalinux9 docker/almalinux/9
            docker build --tag klf-fedora37 docker/fedora/37
            docker build --tag klf-lint docker/lint
            docker image prune --force

  lint:
    needs: docker
    runs-on: [self-hosted, Windows]
    steps:
      - name: Lint sources
        # We need pip installed linter because packaged one ignores config file.
        # We need --login because pip installs to ~/.local/bin and that is added
        # to PATH via .bashrc and that's not read by default.
        # We need ANSIBLE_CONFIG otherwise Ansible complains about word-writable
        # permissions:
        # https://docs.ansible.com/ansible/devel/reference_appendices/config.html#avoiding-security-risks-with-ansible-cfg-in-the-current-directory
        # No, there's no way to make it work with different modes on Windows:
        # https://stackoverflow.com/a/66390200/1708230
        # Then it complains about the log file being read-only, so override it.
        # Simple!
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf:ro klf-lint /bin/bash --login -c
            "yamllint --strict . && ANSIBLE_CONFIG=ansible.cfg ANSIBLE_LOG_PATH=/tmp/ansible.log ansible-lint --strict"

  almalinux-9:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: AlmaLinux 9
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf:ro klf-almalinux9 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=true' <<< y && ./uninstall.sh <<< y && ./install.sh --extra-vars 'skip_kfgame=true kf2_classic=true' <<< y"

  fedora-37:
    needs: lint
    runs-on: [self-hosted, Windows]
    steps:
      - name: Fedora 37
        run: >
            docker run --rm -v ${{ github.workspace }}:/klf:ro klf-fedora37 /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=true' <<< y && ./uninstall.sh <<< y && ./install.sh --extra-vars 'skip_kfgame=true kf2_classic=true' <<< y"
