---
name: Ubuntu 20.04

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  pull_request:
    branches: []

jobs:
  ansible-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obtain sources
        uses: actions/checkout@v3
      - name: Test Galaxy role
        run: >
            CONT_ID=$(podman run --rm -v ${{ github.workspace }}:/repo -v /sys/fs/cgroup:/sys/fs/cgroup:ro
            --tmpfs /tmp --tmpfs /run --privileged --detach bviktor/ansible-systemd-ubuntu:20.04) &&
            podman exec ${CONT_ID} /bin/bash -c
            "./install.sh --extra-vars 'skip_kfgame=true' <<< y &&
            ./uninstall.sh <<< y &&
            ./install.sh --extra-vars 'skip_kfgame=true kf2_classic=true' <<< y" &&
            podman stop ${CONT_ID}
